# Copyright 2025 Amiasys Corporation and/or its affiliates. All rights reserved.
  
services:
  asn-mdb:
    container_name: asn-mdb
    image: mongo:7.0  # the mongodb version
    restart: always   # auto restart the container if it fails
    ulimits:
      nofile: 100000
    environment:
      MONGO_INITDB_ROOT_USERNAME: amia  # db root username,
      MONGO_INITDB_ROOT_PASSWORD: 2022  # db root user password
    ports:
      - "27017:27017"  # port forwarding (localPort:containerPort)
    volumes:
      - ./data/:/data/db  # data volumes, (localDirectory:containerDirectory)
    command: --bind_ip_all --auth
  asn-idb:
    image: influxdb:1.11.8
    container_name: asn-idb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: asn
      INFLUXDB_ADMIN_USER: amia
      INFLUXDB_ADMIN_PASSWORD: 2022
      INFLUXDB_USER: amia
      INFLUXDB_USER_PASSWORD: 2022
  sapphire-ldap:
    image: registry.amiasys.com/iam:v1.1.0
    container_name: sapphire-ldap
    privileged: true
    restart: always
    ports:
      - "18389:389/udp"
      - "18389:389/tcp"
    volumes:
      - ldap_slap:/etc/ldap/slapd.d/
      - ldap_data:/var/lib/ldap/
    command: sh -c "/etc/init.d/slapd start && tail -f /dev/null"
  sapphire-iam:
    image: registry.amiasys.com/sapphire.iam:v25.0.6
    container_name: sapphire-iam
    restart: always
    ports:
      - "17930:17930"
      - "17931:17931"
    depends_on:
      - "sapphire-ldap"
    volumes:
      - ./config/:/usr/local/sapphire/
  asnc:
    restart: always
    image: registry.amiasys.com/asnc:v25.0.18
    network_mode: host
    depends_on:
      - "asn-mdb"
      - "asn-idb"
      - "sapphire-ldap"
      - "sapphire-iam"
    volumes:
      - ./cert/:/asn/cert/
      - ./config/:/asn/config/
      - ./log/:/asn/log/
      - ./plugins:/asn/plugins/

volumes:
  influxdb_data:
    driver: local
  ldap_slap:
    driver: local
  ldap_data:
    driver: local
