# Copyright 2026 Amiasys Corporation and/or its affiliates. All rights reserved.

PACKAGE := asn-service-api/v26
.PHONY: code-inspect

code-inspect:
	goimports -w -local "$(PACKAGE)" .
	go fmt ./...
	errcheck ./...
	go vet ./...
	staticcheck ./...
	golangci-lint run
	@echo "code-inspection completed"
