# Copyright 2025 Amiasys Corporation and/or its affiliates. All rights reserved.

services:
  asnsn:
    restart: always
    image: registry.amiasys.com/asnsn:v25.0.21
    ports:
      - "50052:50052"
    volumes:
      - ./config/:/etc/asnsn/config/
      - ./log/:/var/log/asnsn/
      - ./service:/etc/asnsn/service/
