services:
  asnsn:
    restart: always
    image: registry.amiasys.com/asnsn:v25.0.10
    ports:
      - "50052:50052"
    volumes:
      - ./config/:/asn/config/
      - ./log/:/asn/log/
      - ./plugins:/asn/plugins/
