# Copyright 2025 Amiasys Corporation and/or its affiliates. All rights reserved.

services:
  asnsn:
    restart: always
    image: registry.amiasys.com/asnsn:v25.1.1
    ports:
      - "50052:50052"
    volumes:
      - ./config/:/etc/asn/servicenode/config
      - ./log/:/var/log/asn/servicenode
      - ./services:/usr/local/asn/servicenode/services
