#This is an example file of the LDAP synchronization format.
#You can refer to this file to fill in the format mapping of the external LDAP.
ldap_mapping:
  base_dc: "dc=example,dc=com" # Base search node of LDAP
  entry:
  - ou: "ou=user" # OU information of target LDAP user
    filter: "(title=example)" # Filter of external LDAP. Example: (&(objectClass=organizationalPerson)(title=example)). Default: ""
    external_rdn: "cn"
    external_obj:
      - "inetOrgPerson"
    attributes:
      - external: "cn"  # Attribute name of external LDAP Server
        local: "cn" # Attribute name of local LDAP Server
      - external: "mobile"  
        local: "mobile"
      - external: "email" 
        local: "email" 
    fixed: #Fields that need to be written by default
      - attribute: "title"
        value: "example"